server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:gamedb
    driverClassName: org.h2.Driver
    username: gameUser
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  security:
    user:
      name: gameUser
      password: password

logging:
  config: classpath:log4j2/log4j2.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info

api:
  host:
    baseurl: https://dragonsofmugloar.com

#Available strategies: highestRewardGameStrategy, easiestTaskGameStrategy
game:
  settings:
    goal: 1000
    turnTolerance: 2
    failureTolerance: 5
    minLives: 1
    itemMinPrice: 101
    gameStrategy: highestRewardGameStrategy
